import { createColumnHelper } from "@tanstack/react-table";
import { Text } from "@/components";
import * as z from "zod";
import Link from "next/link";

/* //  Lead generation */
const leadGenerationsSchema = z.object({
  name: z.string(),
  channel: z.string(),
  associatedBrands: z.string(),
  phoneNumber: z.string(),
  email: z.string(),
  lifeTimeSales: z.number(),
});

export type LeadGenerationType = z.infer<typeof leadGenerationsSchema>;

const leadGenerationColumnHelper = createColumnHelper<LeadGenerationType>();

export const leadGenerationColumns = [
  leadGenerationColumnHelper.accessor("name", {
    header: "Affiliates Name",
    cell: (cell) => {
      let id = Math.floor(Math.random() * 1000).toString();
      return (
        <div className="flex items-center gap-5 !w-fit">
          <Link href={`/affiliates/lead/${id}`}>{cell.getValue()}</Link>
        </div>
      );
    },
  }),
  leadGenerationColumnHelper.accessor("channel", {
    header: "Channel",
    cell: (cell) => (
      <div>
        <Text size="8xl" as="p">
          {cell.getValue()}
        </Text>
      </div>
    ),
  }),
  leadGenerationColumnHelper.accessor("associatedBrands", {
    header: "Associated Brand(s)",
    cell: (cell) => (
      <div className="flex flex-col items-center gap-[42px] w-fit">
        <Text size="8xl" as="p">
          {cell.getValue()}
        </Text>
      </div>
    ),
  }),
  leadGenerationColumnHelper.accessor("phoneNumber", {
    header: "Phone Number",
    cell: (cell) => (
      <div className="flex flex-col items-center gap-[42px] w-fit">
        <Text size="8xl" as="p">
          {cell.getValue()}
        </Text>
      </div>
    ),
  }),
  leadGenerationColumnHelper.accessor("email", {
    header: "Email",
    cell: (cell) => (
      <div className="flex flex-col items-center gap-[42px] w-fit">
        <Text size="8xl" as="p">
          {cell.getValue()}
        </Text>
      </div>
    ),
  }),
  leadGenerationColumnHelper.accessor("lifeTimeSales", {
    header: "Lifetime Sales",
    cell: (cell) => (
      <div className="flex flex-col items-center gap-[42px] w-fit">
        <p className="text-2xl font-bold text-yellow-900">${cell.getValue()}</p>
      </div>
    ),
  }),
];

const leadGenerationsData: LeadGenerationType[] = [
  {
    name: "John Doe",
    channel: "Facebook",
    associatedBrands: "Brand 1",
    phoneNumber: "1234567890",
    email: "john.doe@facebook.com",
    lifeTimeSales: 1000,
  },
  {
    name: "Jane Smith",
    channel: "Google",
    associatedBrands: "Brand 2",
    phoneNumber: "1234567891",
    email: "jane.smith@google.com",
    lifeTimeSales: 2000,
  },
  {
    name: "Sam Wilson",
    channel: "Twitter",
    associatedBrands: "Brand 3",
    phoneNumber: "1234567892",
    email: "sam.wilson@twitter.com",
    lifeTimeSales: 1500,
  },
  {
    name: "Peter Parker",
    channel: "Instagram",
    associatedBrands: "Brand 4",
    phoneNumber: "1234567893",
    email: "peter.parker@instagram.com",
    lifeTimeSales: 2500,
  },
  {
    name: "Bruce Wayne",
    channel: "LinkedIn",
    associatedBrands: "Brand 5",
    phoneNumber: "1234567894",
    email: "bruce.wayne@linkedin.com",
    lifeTimeSales: 3000,
  },
  {
    name: "Clark Kent",
    channel: "YouTube",
    associatedBrands: "Brand 6",
    phoneNumber: "1234567895",
    email: "clark.kent@youtube.com",
    lifeTimeSales: 3500,
  },
  {
    name: "Diana Prince",
    channel: "Pinterest",
    associatedBrands: "Brand 7",
    phoneNumber: "1234567896",
    email: "diana.prince@pinterest.com",
    lifeTimeSales: 4000,
  },
  {
    name: "Barry Allen",
    channel: "Snapchat",
    associatedBrands: "Brand 8",
    phoneNumber: "1234567897",
    email: "barry.allen@snapchat.com",
    lifeTimeSales: 4500,
  },
  {
    name: "Hal Jordan",
    channel: "Reddit",
    associatedBrands: "Brand 9",
    phoneNumber: "1234567898",
    email: "hal.jordan@reddit.com",
    lifeTimeSales: 5000,
  },
  {
    name: "Arthur Curry",
    channel: "TikTok",
    associatedBrands: "Brand 10",
    phoneNumber: "1234567899",
    email: "arthur.curry@tiktok.com",
    lifeTimeSales: 5500,
  },
  {
    name: "Victor Stone",
    channel: "Tumblr",
    associatedBrands: "Brand 11",
    phoneNumber: "1234567800",
    email: "victor.stone@tumblr.com",
    lifeTimeSales: 6000,
  },
  {
    name: "Oliver Queen",
    channel: "Quora",
    associatedBrands: "Brand 12",
    phoneNumber: "1234567801",
    email: "oliver.queen@quora.com",
    lifeTimeSales: 6500,
  },
  {
    name: "Tony Stark",
    channel: "WhatsApp",
    associatedBrands: "Brand 13",
    phoneNumber: "1234567802",
    email: "tony.stark@whatsapp.com",
    lifeTimeSales: 7000,
  },
  {
    name: "Steve Rogers",
    channel: "Telegram",
    associatedBrands: "Brand 14",
    phoneNumber: "1234567803",
    email: "steve.rogers@telegram.com",
    lifeTimeSales: 7500,
  },
  {
    name: "Natasha Romanoff",
    channel: "Viber",
    associatedBrands: "Brand 15",
    phoneNumber: "1234567804",
    email: "natasha.romanoff@viber.com",
    lifeTimeSales: 8000,
  },
  {
    name: "Wanda Maximoff",
    channel: "WeChat",
    associatedBrands: "Brand 16",
    phoneNumber: "1234567805",
    email: "wanda.maximoff@wechat.com",
    lifeTimeSales: 8500,
  },
  {
    name: "Stephen Strange",
    channel: "Line",
    associatedBrands: "Brand 17",
    phoneNumber: "1234567806",
    email: "stephen.strange@line.com",
    lifeTimeSales: 9000,
  },
  {
    name: "T'Challa",
    channel: "Skype",
    associatedBrands: "Brand 18",
    phoneNumber: "1234567807",
    email: "tchalla@skype.com",
    lifeTimeSales: 9500,
  },
  {
    name: "Bruce Banner",
    channel: "Messenger",
    associatedBrands: "Brand 19",
    phoneNumber: "1234567808",
    email: "bruce.banner@messenger.com",
    lifeTimeSales: 10000,
  },
  {
    name: "Scott Lang",
    channel: "Discord",
    associatedBrands: "Brand 20",
    phoneNumber: "1234567809",
    email: "scott.lang@discord.com",
    lifeTimeSales: 10500,
  },
  {
    name: "Hope van Dyne",
    channel: "Slack",
    associatedBrands: "Brand 21",
    phoneNumber: "1234567810",
    email: "hope.vandyne@slack.com",
    lifeTimeSales: 11000,
  },
  {
    name: "Carol Danvers",
    channel: "Signal",
    associatedBrands: "Brand 22",
    phoneNumber: "1234567811",
    email: "carol.danvers@signal.com",
    lifeTimeSales: 11500,
  },
  {
    name: "Peter Quill",
    channel: "Kik",
    associatedBrands: "Brand 23",
    phoneNumber: "1234567812",
    email: "peter.quill@kik.com",
    lifeTimeSales: 12000,
  },
  {
    name: "Gamora",
    channel: "Foursquare",
    associatedBrands: "Brand 24",
    phoneNumber: "1234567813",
    email: "gamora@foursquare.com",
    lifeTimeSales: 12500,
  },
  {
    name: "Drax",
    channel: "Myspace",
    associatedBrands: "Brand 25",
    phoneNumber: "1234567814",
    email: "drax@myspace.com",
    lifeTimeSales: 13000,
  },
  {
    name: "Rocket Raccoon",
    channel: "Blogger",
    associatedBrands: "Brand 26",
    phoneNumber: "1234567815",
    email: "rocket@blogger.com",
    lifeTimeSales: 13500,
  },
  {
    name: "Groot",
    channel: "WordPress",
    associatedBrands: "Brand 27",
    phoneNumber: "1234567816",
    email: "groot@wordpress.com",
    lifeTimeSales: 14000,
  },
  {
    name: "Thanos",
    channel: "LinkedIn",
    associatedBrands: "Brand 28",
    phoneNumber: "1234567817",
    email: "thanos@linkedin.com",
    lifeTimeSales: 14500,
  },
  {
    name: "Loki",
    channel: "Reddit",
    associatedBrands: "Brand 29",
    phoneNumber: "1234567818",
    email: "loki@reddit.com",
    lifeTimeSales: 15000,
  },
  {
    name: "Thor",
    channel: "Facebook",
    associatedBrands: "Brand 30",
    phoneNumber: "1234567819",
    email: "thor@facebook.com",
    lifeTimeSales: 15500,
  },
  {
    name: "Hawkeye",
    channel: "Twitter",
    associatedBrands: "Brand 31",
    phoneNumber: "1234567820",
    email: "hawkeye@twitter.com",
    lifeTimeSales: 16000,
  },
  {
    name: "Vision",
    channel: "Instagram",
    associatedBrands: "Brand 32",
    phoneNumber: "1234567821",
    email: "vision@instagram.com",
    lifeTimeSales: 16500,
  },
  {
    name: "Bucky Barnes",
    channel: "Snapchat",
    associatedBrands: "Brand 33",
    phoneNumber: "1234567822",
    email: "bucky.barnes@snapchat.com",
    lifeTimeSales: 17000,
  },
  {
    name: "Sam Wilson",
    channel: "Pinterest",
    associatedBrands: "Brand 34",
    phoneNumber: "1234567823",
    email: "sam.wilson@pinterest.com",
    lifeTimeSales: 17500,
  },
  {
    name: "Wanda Maximoff",
    channel: "WhatsApp",
    associatedBrands: "Brand 35",
    phoneNumber: "1234567824",
    email: "wanda.maximoff@whatsapp.com",
    lifeTimeSales: 18000,
  },
  {
    name: "Shuri",
    channel: "Telegram",
    associatedBrands: "Brand 36",
    phoneNumber: "1234567825",
    email: "shuri@telegram.com",
    lifeTimeSales: 18500,
  },
  {
    name: "T'Challa",
    channel: "Viber",
    associatedBrands: "Brand 37",
    phoneNumber: "1234567826",
    email: "tchalla@viber.com",
    lifeTimeSales: 19000,
  },
  {
    name: "Killmonger",
    channel: "WeChat",
    associatedBrands: "Brand 38",
    phoneNumber: "1234567827",
    email: "killmonger@wechat.com",
    lifeTimeSales: 19500,
  },
  {
    name: "Okoye",
    channel: "Line",
    associatedBrands: "Brand 39",
    phoneNumber: "1234567828",
    email: "okoye@line.com",
    lifeTimeSales: 20000,
  },
  {
    name: "M'Baku",
    channel: "Skype",
    associatedBrands: "Brand 40",
    phoneNumber: "1234567829",
    email: "mbaku@skype.com",
    lifeTimeSales: 20500,
  },
  {
    name: "Nakia",
    channel: "Messenger",
    associatedBrands: "Brand 41",
    phoneNumber: "1234567830",
    email: "nakia@messenger.com",
    lifeTimeSales: 21000,
  },
  {
    name: "Suri",
    channel: "Discord",
    associatedBrands: "Brand 42",
    phoneNumber: "1234567831",
    email: "suri@discord.com",
    lifeTimeSales: 21500,
  },
  {
    name: "Ramonda",
    channel: "Slack",
    associatedBrands: "Brand 43",
    phoneNumber: "1234567832",
    email: "ramonda@slack.com",
    lifeTimeSales: 22000,
  },
  {
    name: "Ross",
    channel: "Signal",
    associatedBrands: "Brand 44",
    phoneNumber: "1234567833",
    email: "ross@signal.com",
    lifeTimeSales: 22500,
  },
  {
    name: "Nick Fury",
    channel: "Kik",
    associatedBrands: "Brand 45",
    phoneNumber: "1234567834",
    email: "nick.fury@kik.com",
    lifeTimeSales: 23000,
  },
  {
    name: "Maria Hill",
    channel: "Foursquare",
    associatedBrands: "Brand 46",
    phoneNumber: "1234567835",
    email: "maria.hill@foursquare.com",
    lifeTimeSales: 23500,
  },
  {
    name: "Phil Coulson",
    channel: "Myspace",
    associatedBrands: "Brand 47",
    phoneNumber: "1234567836",
    email: "phil.coulson@myspace.com",
    lifeTimeSales: 24000,
  },
  {
    name: "Peggy Carter",
    channel: "Blogger",
    associatedBrands: "Brand 48",
    phoneNumber: "1234567837",
    email: "peggy.carter@blogger.com",
    lifeTimeSales: 24500,
  },
  {
    name: "Sharon Carter",
    channel: "WordPress",
    associatedBrands: "Brand 49",
    phoneNumber: "1234567838",
    email: "sharon.carter@wordpress.com",
    lifeTimeSales: 25000,
  },
  {
    name: "Heimdall",
    channel: "LinkedIn",
    associatedBrands: "Brand 50",
    phoneNumber: "1234567839",
    email: "heimdall@linkedin.com",
    lifeTimeSales: 25500,
  },
  {
    name: "Odin",
    channel: "Reddit",
    associatedBrands: "Brand 51",
    phoneNumber: "1234567840",
    email: "odin@reddit.com",
    lifeTimeSales: 26000,
  },
  {
    name: "Frigga",
    channel: "Facebook",
    associatedBrands: "Brand 52",
    phoneNumber: "1234567841",
    email: "frigga@facebook.com",
    lifeTimeSales: 26500,
  },
  {
    name: "Hela",
    channel: "Twitter",
    associatedBrands: "Brand 53",
    phoneNumber: "1234567842",
    email: "hela@twitter.com",
    lifeTimeSales: 27000,
  },
  {
    name: "Laufey",
    channel: "Instagram",
    associatedBrands: "Brand 54",
    phoneNumber: "1234567843",
    email: "laufey@instagram.com",
    lifeTimeSales: 27500,
  },
  {
    name: "Sif",
    channel: "Snapchat",
    associatedBrands: "Brand 55",
    phoneNumber: "1234567844",
    email: "sif@snapchat.com",
    lifeTimeSales: 28000,
  },
  {
    name: "Volstagg",
    channel: "Pinterest",
    associatedBrands: "Brand 56",
    phoneNumber: "1234567845",
    email: "volstagg@pinterest.com",
    lifeTimeSales: 28500,
  },
  {
    name: "Fandral",
    channel: "WhatsApp",
    associatedBrands: "Brand 57",
    phoneNumber: "1234567846",
    email: "fandral@whatsapp.com",
    lifeTimeSales: 29000,
  },
];

/* //  Contact templates */
const contactTemplatesSchema = z.object({
  templateName: z.string(),
  subject: z.string(),
  body: z.string(),
  createdBy: z.string(),
  createdAt: z.string(),
});

export type ContactTemplateType = z.infer<typeof contactTemplatesSchema>;

const contactTemplateColumnHelper = createColumnHelper<ContactTemplateType>();

export const contactTemplateColumns = [
  contactTemplateColumnHelper.accessor("templateName", {
    header: "Template Name",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  contactTemplateColumnHelper.accessor("subject", {
    header: "Subject",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  contactTemplateColumnHelper.accessor("body", {
    header: "Body",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  contactTemplateColumnHelper.accessor("createdBy", {
    header: "Created By",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  contactTemplateColumnHelper.accessor("createdAt", {
    header: "Created At",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
];

const contactTemplatesData: ContactTemplateType[] = [
  {
    templateName: "Welcome Email",
    subject: "Welcome to Our Platform",
    body: "Hello, thank you for joining us. We are excited to have you on board...",
    createdBy: "Admin",
    createdAt: "2023-01-01",
  },
  {
    templateName: "Thank You Email",
    subject: "Thank You for Your Purchase",
    body: "Hi there, thank you for your recent purchase. We hope you enjoy...",
    createdBy: "Admin",
    createdAt: "2023-01-02",
  },
  {
    templateName: "Reminder Email",
    subject: "Don't Forget About Your Upcoming Appointment",
    body: "Just a friendly reminder about your upcoming appointment on...",
    createdBy: "Support Team",
    createdAt: "2023-01-03",
  },
  {
    templateName: "Follow-up Email",
    subject: "We'd Love to Hear Your Feedback",
    body: "Hi, we hope you are enjoying our service. We would love to hear your feedback...",
    createdBy: "Customer Service",
    createdAt: "2023-01-04",
  },
  {
    templateName: "Promotion Email",
    subject: "Exclusive Offer Just for You",
    body: "Hello, we have an exclusive offer for our valued customers...",
    createdBy: "Marketing",
    createdAt: "2023-01-05",
  },
  {
    templateName: "Survey Email",
    subject: "Please Take Our Survey",
    body: "We value your opinion. Please take a moment to complete our survey...",
    createdBy: "Research Team",
    createdAt: "2023-01-06",
  },
  {
    templateName: "Newsletter",
    subject: "Monthly News and Updates",
    body: "Welcome to our monthly newsletter. Here are the latest updates...",
    createdBy: "Editor",
    createdAt: "2023-01-07",
  },
  {
    templateName: "Event Invitation",
    subject: "You're Invited to Our Special Event",
    body: "We are pleased to invite you to our special event happening on...",
    createdBy: "Events Team",
    createdAt: "2023-01-08",
  },
  {
    templateName: "Account Update",
    subject: "Important Information About Your Account",
    body: "Dear user, we have important information regarding your account...",
    createdBy: "Admin",
    createdAt: "2023-01-09",
  },
  {
    templateName: "Password Reset",
    subject: "Reset Your Password",
    body: "Click the link below to reset your password...",
    createdBy: "Support Team",
    createdAt: "2023-01-10",
  },
  {
    templateName: "Billing Reminder",
    subject: "Your Invoice is Due Soon",
    body: "This is a reminder that your invoice is due on...",
    createdBy: "Billing Department",
    createdAt: "2023-01-11",
  },
  {
    templateName: "Holiday Greeting",
    subject: "Happy Holidays from All of Us",
    body: "Wishing you a wonderful holiday season...",
    createdBy: "HR Team",
    createdAt: "2023-01-12",
  },
  {
    templateName: "Service Announcement",
    subject: "New Features Coming Soon",
    body: "We are excited to announce new features coming to our platform...",
    createdBy: "Product Team",
    createdAt: "2023-01-13",
  },
  {
    templateName: "Welcome Aboard",
    subject: "Welcome to the Team",
    body: "We are thrilled to have you join our team. Here are some resources...",
    createdBy: "HR Team",
    createdAt: "2023-01-14",
  },
  {
    templateName: "Order Confirmation",
    subject: "Your Order Has Been Confirmed",
    body: "Thank you for your order. Here are the details...",
    createdBy: "Sales Team",
    createdAt: "2023-01-15",
  },
  {
    templateName: "Shipping Notification",
    subject: "Your Order Has Shipped",
    body: "Your order has shipped. Here is the tracking information...",
    createdBy: "Shipping Department",
    createdAt: "2023-01-16",
  },
  {
    templateName: "Refund Processed",
    subject: "Your Refund Has Been Processed",
    body: "We have processed your refund. Here are the details...",
    createdBy: "Finance Team",
    createdAt: "2023-01-17",
  },
  {
    templateName: "Appointment Confirmation",
    subject: "Your Appointment is Confirmed",
    body: "Your appointment is confirmed for...",
    createdBy: "Support Team",
    createdAt: "2023-01-18",
  },
  {
    templateName: "Upgrade Notification",
    subject: "Your Account Has Been Upgraded",
    body: "Congratulations, your account has been upgraded. Enjoy the new features...",
    createdBy: "Admin",
    createdAt: "2023-01-19",
  },
  {
    templateName: "Downgrade Notification",
    subject: "Your Account Has Been Downgraded",
    body: "Your account has been downgraded. If you have any questions, contact us...",
    createdBy: "Admin",
    createdAt: "2023-01-20",
  },
  {
    templateName: "Payment Receipt",
    subject: "Your Payment Receipt",
    body: "Thank you for your payment. Here is your receipt...",
    createdBy: "Finance Team",
    createdAt: "2023-01-21",
  },
  {
    templateName: "Trial Ending",
    subject: "Your Trial is Ending Soon",
    body: "Your trial period is ending soon. Consider upgrading to continue...",
    createdBy: "Marketing",
    createdAt: "2023-01-22",
  },
  {
    templateName: "Support Ticket Update",
    subject: "Update on Your Support Ticket",
    body: "We have an update on your support ticket...",
    createdBy: "Support Team",
    createdAt: "2023-01-23",
  },
  {
    templateName: "Account Deactivation",
    subject: "Your Account Has Been Deactivated",
    body: "Your account has been deactivated due to inactivity...",
    createdBy: "Admin",
    createdAt: "2023-01-24",
  },
  {
    templateName: "Service Disruption",
    subject: "Notice of Service Disruption",
    body: "We are currently experiencing a service disruption. We are working to resolve it...",
    createdBy: "Support Team",
    createdAt: "2023-01-25",
  },
  {
    templateName: "Subscription Renewal",
    subject: "Your Subscription is Renewing Soon",
    body: "Your subscription is set to renew on...",
    createdBy: "Billing Department",
    createdAt: "2023-01-26",
  },
  {
    templateName: "Event Reminder",
    subject: "Reminder: Upcoming Event",
    body: "Just a reminder about the upcoming event...",
    createdBy: "Events Team",
    createdAt: "2023-01-27",
  },
  {
    templateName: "Feedback Request",
    subject: "We'd Love Your Feedback",
    body: "Please take a moment to provide your feedback...",
    createdBy: "Customer Service",
    createdAt: "2023-01-28",
  },
  {
    templateName: "Product Launch",
    subject: "New Product Launch",
    body: "We are excited to announce the launch of our new product...",
    createdBy: "Product Team",
    createdAt: "2023-01-29",
  },
  {
    templateName: "Webinar Invitation",
    subject: "Join Our Upcoming Webinar",
    body: "You are invited to join our upcoming webinar on...",
    createdBy: "Marketing",
    createdAt: "2023-01-30",
  },
  {
    templateName: "Training Session",
    subject: "Upcoming Training Session",
    body: "We have an upcoming training session on...",
    createdBy: "HR Team",
    createdAt: "2023-01-31",
  },
  {
    templateName: "Account Verification",
    subject: "Verify Your Account",
    body: "Please verify your account by clicking the link below...",
    createdBy: "Admin",
    createdAt: "2023-02-01",
  },
  {
    templateName: "Welcome Back",
    subject: "Welcome Back to Our Platform",
    body: "We are glad to see you back. Here are some new features...",
    createdBy: "Support Team",
    createdAt: "2023-02-02",
  },
  {
    templateName: "Job Application Received",
    subject: "We Have Received Your Application",
    body: "Thank you for applying. We have received your application and will review it...",
    createdBy: "HR Team",
    createdAt: "2023-02-03",
  },
  {
    templateName: "Interview Invitation",
    subject: "Invitation to Interview",
    body: "We would like to invite you to an interview for the position of...",
    createdBy: "HR Team",
    createdAt: "2023-02-04",
  },
  {
    templateName: "Job Offer",
    subject: "Job Offer",
    body: "We are pleased to offer you the position of...",
    createdBy: "HR Team",
    createdAt: "2023-02-05",
  },
  {
    templateName: "Onboarding Instructions",
    subject: "Onboarding Instructions",
    body: "Welcome to the team. Here are your onboarding instructions...",
    createdBy: "HR Team",
    createdAt: "2023-02-06",
  },
  {
    templateName: "Training Reminder",
    subject: "Reminder: Upcoming Training",
    body: "This is a reminder about your upcoming training session...",
    createdBy: "HR Team",
    createdAt: "2023-02-07",
  },
  {
    templateName: "Performance Review",
    subject: "Performance Review Scheduled",
    body: "Your performance review has been scheduled for...",
    createdBy: "HR Team",
    createdAt: "2023-02-08",
  },
  {
    templateName: "Meeting Reminder",
    subject: "Reminder: Upcoming Meeting",
    body: "This is a reminder about your upcoming meeting on...",
    createdBy: "Support Team",
    createdAt: "2023-02-09",
  },
  {
    templateName: "Project Update",
    subject: "Project Update",
    body: "Here is an update on the current project...",
    createdBy: "Project Manager",
    createdAt: "2023-02-10",
  },
  {
    templateName: "Milestone Achieved",
    subject: "Congratulations on Achieving the Milestone",
    body: "Congratulations! You have achieved the project milestone...",
    createdBy: "Project Manager",
    createdAt: "2023-02-11",
  },
  {
    templateName: "Client Follow-Up",
    subject: "Follow-Up on Our Recent Discussion",
    body: "Hi, I wanted to follow up on our recent discussion...",
    createdBy: "Sales Team",
    createdAt: "2023-02-12",
  },
  {
    templateName: "Contract Renewal",
    subject: "Your Contract is Up for Renewal",
    body: "Your contract is up for renewal. Please review the details...",
    createdBy: "Legal Team",
    createdAt: "2023-02-13",
  },
  {
    templateName: "New Feature Announcement",
    subject: "Announcing New Features",
    body: "We are excited to announce the following new features...",
    createdBy: "Product Team",
    createdAt: "2023-02-14",
  },
  {
    templateName: "Service Upgrade",
    subject: "Your Service Has Been Upgraded",
    body: "Your service has been upgraded to include...",
    createdBy: "Support Team",
    createdAt: "2023-02-15",
  },
  {
    templateName: "Service Downgrade",
    subject: "Your Service Has Been Downgraded",
    body: "Your service has been downgraded. If you have any questions...",
    createdBy: "Support Team",
    createdAt: "2023-02-16",
  },
  {
    templateName: "Holiday Hours",
    subject: "Holiday Hours Notification",
    body: "Please be informed of our holiday hours...",
    createdBy: "Admin",
    createdAt: "2023-02-17",
  },
  {
    templateName: "Service Renewal",
    subject: "Your Service is Renewing Soon",
    body: "Your service is set to renew on...",
    createdBy: "Billing Department",
    createdAt: "2023-02-18",
  },
  {
    templateName: "Data Privacy Update",
    subject: "Important Update on Data Privacy",
    body: "We have updated our data privacy policy. Please review the changes...",
    createdBy: "Legal Team",
    createdAt: "2023-02-19",
  },
  {
    templateName: "System Maintenance",
    subject: "Scheduled System Maintenance",
    body: "We have scheduled system maintenance on...",
    createdBy: "IT Team",
    createdAt: "2023-02-20",
  },
  {
    templateName: "Bug Fix Announcement",
    subject: "Recent Bug Fixes",
    body: "We have fixed several bugs in our system. Here are the details...",
    createdBy: "Product Team",
    createdAt: "2023-02-21",
  },
  {
    templateName: "Downtime Notification",
    subject: "Notice of Scheduled Downtime",
    body: "We will be experiencing scheduled downtime on...",
    createdBy: "IT Team",
    createdAt: "2023-02-22",
  },
  {
    templateName: "Security Update",
    subject: "Important Security Update",
    body: "We have implemented an important security update. Please review...",
    createdBy: "IT Team",
    createdAt: "2023-02-23",
  },
];

/* //  Agreement templates */
const agreementTemplatesSchema = z.object({
  agreementName: z.string(),
  version: z.string(),
  effectiveDate: z.string(),
  createdBy: z.string(),
  status: z.string(),
});

export type AgreementTemplateType = z.infer<typeof agreementTemplatesSchema>;

const agreementTemplateColumnHelper =
  createColumnHelper<AgreementTemplateType>();

export const agreementTemplateColumns = [
  agreementTemplateColumnHelper.accessor("agreementName", {
    header: "Agreement Name",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  agreementTemplateColumnHelper.accessor("version", {
    header: "Version",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  agreementTemplateColumnHelper.accessor("effectiveDate", {
    header: "Effective Date",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  agreementTemplateColumnHelper.accessor("createdBy", {
    header: "Created By",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  agreementTemplateColumnHelper.accessor("status", {
    header: "Status",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
];

const agreementTemplatesData: AgreementTemplateType[] = [
  {
    agreementName: "Non-Disclosure Agreement",
    version: "1.0",
    effectiveDate: "2023-01-01",
    createdBy: "Legal Team",
    status: "Active",
  },
  {
    agreementName: "Service Agreement",
    version: "1.1",
    effectiveDate: "2023-01-15",
    createdBy: "Legal Team",
    status: "Active",
  },
  {
    agreementName: "Partnership Agreement",
    version: "2.0",
    effectiveDate: "2023-02-01",
    createdBy: "Business Development",
    status: "Pending",
  },
  {
    agreementName: "Employment Contract",
    version: "3.1",
    effectiveDate: "2023-02-15",
    createdBy: "HR Team",
    status: "Active",
  },
  {
    agreementName: "Lease Agreement",
    version: "2.2",
    effectiveDate: "2023-03-01",
    createdBy: "Property Management",
    status: "Active",
  },
  {
    agreementName: "Consultant Agreement",
    version: "1.3",
    effectiveDate: "2023-03-15",
    createdBy: "Legal Team",
    status: "Expired",
  },
  {
    agreementName: "Sales Agreement",
    version: "4.0",
    effectiveDate: "2023-04-01",
    createdBy: "Sales Team",
    status: "Active",
  },
  {
    agreementName: "Purchase Agreement",
    version: "3.2",
    effectiveDate: "2023-04-15",
    createdBy: "Procurement",
    status: "Active",
  },
  {
    agreementName: "Loan Agreement",
    version: "2.3",
    effectiveDate: "2023-05-01",
    createdBy: "Finance Team",
    status: "Pending",
  },
  {
    agreementName: "Licensing Agreement",
    version: "5.0",
    effectiveDate: "2023-05-15",
    createdBy: "Legal Team",
    status: "Expired",
  },
  {
    agreementName: "Distribution Agreement",
    version: "1.4",
    effectiveDate: "2023-06-01",
    createdBy: "Logistics",
    status: "Active",
  },
  {
    agreementName: "Maintenance Agreement",
    version: "2.1",
    effectiveDate: "2023-06-15",
    createdBy: "Maintenance Team",
    status: "Active",
  },
  {
    agreementName: "Joint Venture Agreement",
    version: "1.5",
    effectiveDate: "2023-07-01",
    createdBy: "Business Development",
    status: "Pending",
  },
  {
    agreementName: "Confidentiality Agreement",
    version: "1.2",
    effectiveDate: "2023-07-15",
    createdBy: "Legal Team",
    status: "Expired",
  },
  {
    agreementName: "Sponsorship Agreement",
    version: "3.3",
    effectiveDate: "2023-08-01",
    createdBy: "Marketing Team",
    status: "Active",
  },
  {
    agreementName: "Affiliate Agreement",
    version: "4.1",
    effectiveDate: "2023-08-15",
    createdBy: "Affiliate Team",
    status: "Active",
  },
  {
    agreementName: "Rental Agreement",
    version: "2.4",
    effectiveDate: "2023-09-01",
    createdBy: "Property Management",
    status: "Pending",
  },
  {
    agreementName: "Agency Agreement",
    version: "3.4",
    effectiveDate: "2023-09-15",
    createdBy: "Business Development",
    status: "Expired",
  },
  {
    agreementName: "Contractor Agreement",
    version: "1.6",
    effectiveDate: "2023-10-01",
    createdBy: "HR Team",
    status: "Active",
  },
  {
    agreementName: "Reseller Agreement",
    version: "5.1",
    effectiveDate: "2023-10-15",
    createdBy: "Sales Team",
    status: "Active",
  },
  {
    agreementName: "Settlement Agreement",
    version: "2.5",
    effectiveDate: "2023-11-01",
    createdBy: "Legal Team",
    status: "Pending",
  },
  {
    agreementName: "Royalty Agreement",
    version: "3.5",
    effectiveDate: "2023-11-15",
    createdBy: "Finance Team",
    status: "Expired",
  },
  {
    agreementName: "Warranty Agreement",
    version: "4.2",
    effectiveDate: "2023-12-01",
    createdBy: "Customer Service",
    status: "Active",
  },
  {
    agreementName: "Non-Compete Agreement",
    version: "1.7",
    effectiveDate: "2023-12-15",
    createdBy: "Legal Team",
    status: "Active",
  },
  {
    agreementName: "Subcontractor Agreement",
    version: "3.6",
    effectiveDate: "2024-01-01",
    createdBy: "HR Team",
    status: "Pending",
  },
  {
    agreementName: "Indemnity Agreement",
    version: "2.6",
    effectiveDate: "2024-01-15",
    createdBy: "Legal Team",
    status: "Expired",
  },
  {
    agreementName: "Franchise Agreement",
    version: "4.3",
    effectiveDate: "2024-02-01",
    createdBy: "Business Development",
    status: "Active",
  },
  {
    agreementName: "End-User License Agreement",
    version: "1.8",
    effectiveDate: "2024-02-15",
    createdBy: "Legal Team",
    status: "Active",
  },
  {
    agreementName: "Data Sharing Agreement",
    version: "3.7",
    effectiveDate: "2024-03-01",
    createdBy: "IT Team",
    status: "Pending",
  },
  {
    agreementName: "Collaboration Agreement",
    version: "2.7",
    effectiveDate: "2024-03-15",
    createdBy: "Business Development",
    status: "Expired",
  },
  {
    agreementName: "Mutual Aid Agreement",
    version: "4.4",
    effectiveDate: "2024-04-01",
    createdBy: "Legal Team",
    status: "Active",
  },
  {
    agreementName: "Subscription Agreement",
    version: "1.9",
    effectiveDate: "2024-04-15",
    createdBy: "Sales Team",
    status: "Active",
  },
  {
    agreementName: "Guarantee Agreement",
    version: "3.8",
    effectiveDate: "2024-05-01",
    createdBy: "Finance Team",
    status: "Pending",
  },
  {
    agreementName: "Team Agreement",
    version: "2.8",
    effectiveDate: "2024-05-15",
    createdBy: "HR Team",
    status: "Expired",
  },
  {
    agreementName: "Severance Agreement",
    version: "4.5",
    effectiveDate: "2024-06-01",
    createdBy: "HR Team",
    status: "Active",
  },
  {
    agreementName: "Volunteer Agreement",
    version: "2.9",
    effectiveDate: "2024-06-15",
    createdBy: "HR Team",
    status: "Active",
  },
  {
    agreementName: "Settlement Agreement",
    version: "1.10",
    effectiveDate: "2024-07-01",
    createdBy: "Legal Team",
    status: "Pending",
  },
  {
    agreementName: "Amendment Agreement",
    version: "3.9",
    effectiveDate: "2024-07-15",
    createdBy: "Legal Team",
    status: "Expired",
  },
  {
    agreementName: "Referral Agreement",
    version: "4.6",
    effectiveDate: "2024-08-01",
    createdBy: "Sales Team",
    status: "Active",
  },
  {
    agreementName: "Access Agreement",
    version: "1.11",
    effectiveDate: "2024-08-15",
    createdBy: "IT Team",
    status: "Active",
  },
  {
    agreementName: "Affiliate Agreement",
    version: "2.10",
    effectiveDate: "2024-09-01",
    createdBy: "Affiliate Team",
    status: "Pending",
  },
  {
    agreementName: "Payment Agreement",
    version: "3.10",
    effectiveDate: "2024-09-15",
    createdBy: "Finance Team",
    status: "Expired",
  },
  {
    agreementName: "Transfer Agreement",
    version: "4.7",
    effectiveDate: "2024-10-01",
    createdBy: "Logistics",
    status: "Active",
  },
];

/* //  Onboarding */
const onboardingSchema = z.object({
  step: z.string(),
  description: z.string(),
  assignedTo: z.string(),
  dueDate: z.string(),
  status: z.string(),
});

export type OnboardingType = z.infer<typeof onboardingSchema>;

const onboardingColumnHelper = createColumnHelper<OnboardingType>();

export const onboardingColumns = [
  onboardingColumnHelper.accessor("step", {
    header: "Step",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  onboardingColumnHelper.accessor("description", {
    header: "Description",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  onboardingColumnHelper.accessor("assignedTo", {
    header: "Assigned To",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  onboardingColumnHelper.accessor("dueDate", {
    header: "Due Date",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
  onboardingColumnHelper.accessor("status", {
    header: "Status",
    cell: (cell) => <div>{cell.getValue()}</div>,
  }),
];

const onboardingData: OnboardingType[] = [
  {
    step: "Step 1",
    description: "Complete the initial survey",
    assignedTo: "John Doe",
    dueDate: "2024-01-01",
    status: "Pending",
  },
  {
    step: "Step 2",
    description: "Upload required documents",
    assignedTo: "Jane Smith",
    dueDate: "2024-01-05",
    status: "Completed",
  },
  {
    step: "Step 3",
    description: "Set up company email",
    assignedTo: "Sam Wilson",
    dueDate: "2024-01-10",
    status: "In Progress",
  },
  {
    step: "Step 4",
    description: "Attend orientation session",
    assignedTo: "Peter Parker",
    dueDate: "2024-01-15",
    status: "Pending",
  },
  {
    step: "Step 5",
    description: "Review company policies",
    assignedTo: "Bruce Wayne",
    dueDate: "2024-01-20",
    status: "Pending",
  },
  {
    step: "Step 6",
    description: "Set up workspace",
    assignedTo: "Clark Kent",
    dueDate: "2024-01-25",
    status: "Completed",
  },
  {
    step: "Step 7",
    description: "Meet the team",
    assignedTo: "Diana Prince",
    dueDate: "2024-01-30",
    status: "Pending",
  },
  {
    step: "Step 8",
    description: "Complete first assignment",
    assignedTo: "Barry Allen",
    dueDate: "2024-02-01",
    status: "In Progress",
  },
  {
    step: "Step 9",
    description: "Set up direct deposit",
    assignedTo: "Hal Jordan",
    dueDate: "2024-02-05",
    status: "Completed",
  },
  {
    step: "Step 10",
    description: "Schedule 1:1 with manager",
    assignedTo: "Arthur Curry",
    dueDate: "2024-02-10",
    status: "Pending",
  },
  {
    step: "Step 11",
    description: "Complete compliance training",
    assignedTo: "Victor Stone",
    dueDate: "2024-02-15",
    status: "Pending",
  },
  {
    step: "Step 12",
    description: "Set up VPN access",
    assignedTo: "Oliver Queen",
    dueDate: "2024-02-20",
    status: "Completed",
  },
  {
    step: "Step 13",
    description: "Enroll in benefits",
    assignedTo: "Tony Stark",
    dueDate: "2024-02-25",
    status: "Pending",
  },
  {
    step: "Step 14",
    description: "Complete security training",
    assignedTo: "Steve Rogers",
    dueDate: "2024-03-01",
    status: "In Progress",
  },
  {
    step: "Step 15",
    description: "Review project guidelines",
    assignedTo: "Natasha Romanoff",
    dueDate: "2024-03-05",
    status: "Pending",
  },
  {
    step: "Step 16",
    description: "Submit project plan",
    assignedTo: "Wanda Maximoff",
    dueDate: "2024-03-10",
    status: "Completed",
  },
  {
    step: "Step 17",
    description: "Attend team lunch",
    assignedTo: "Stephen Strange",
    dueDate: "2024-03-15",
    status: "Pending",
  },
  {
    step: "Step 18",
    description: "Complete setup of software tools",
    assignedTo: "T'Challa",
    dueDate: "2024-03-20",
    status: "In Progress",
  },
  {
    step: "Step 19",
    description: "Review client list",
    assignedTo: "Bruce Banner",
    dueDate: "2024-03-25",
    status: "Pending",
  },
  {
    step: "Step 20",
    description: "Set up project management tool",
    assignedTo: "Scott Lang",
    dueDate: "2024-03-30",
    status: "Completed",
  },
  {
    step: "Step 21",
    description: "Complete market research",
    assignedTo: "Hope van Dyne",
    dueDate: "2024-04-01",
    status: "Pending",
  },
  {
    step: "Step 22",
    description: "Prepare presentation",
    assignedTo: "Carol Danvers",
    dueDate: "2024-04-05",
    status: "In Progress",
  },
  {
    step: "Step 23",
    description: "Attend client meeting",
    assignedTo: "Peter Quill",
    dueDate: "2024-04-10",
    status: "Pending",
  },
  {
    step: "Step 24",
    description: "Submit expense report",
    assignedTo: "Gamora",
    dueDate: "2024-04-15",
    status: "Completed",
  },
  {
    step: "Step 25",
    description: "Complete performance review",
    assignedTo: "Drax",
    dueDate: "2024-04-20",
    status: "Pending",
  },
  {
    step: "Step 26",
    description: "Prepare for quarterly review",
    assignedTo: "Rocket Raccoon",
    dueDate: "2024-04-25",
    status: "In Progress",
  },
  {
    step: "Step 27",
    description: "Complete quarterly review",
    assignedTo: "Groot",
    dueDate: "2024-04-30",
    status: "Pending",
  },
  {
    step: "Step 28",
    description: "Review annual goals",
    assignedTo: "Thanos",
    dueDate: "2024-05-01",
    status: "Completed",
  },
  {
    step: "Step 29",
    description: "Set up annual budget",
    assignedTo: "Loki",
    dueDate: "2024-05-05",
    status: "Pending",
  },
  {
    step: "Step 30",
    description: "Complete budget review",
    assignedTo: "Thor",
    dueDate: "2024-05-10",
    status: "In Progress",
  },
  {
    step: "Step 31",
    description: "Submit budget proposal",
    assignedTo: "Hawkeye",
    dueDate: "2024-05-15",
    status: "Pending",
  },
  {
    step: "Step 32",
    description: "Complete annual report",
    assignedTo: "Vision",
    dueDate: "2024-05-20",
    status: "Completed",
  },
  {
    step: "Step 33",
    description: "Prepare for audit",
    assignedTo: "Bucky Barnes",
    dueDate: "2024-05-25",
    status: "Pending",
  },
  {
    step: "Step 34",
    description: "Complete audit preparation",
    assignedTo: "Sam Wilson",
    dueDate: "2024-05-30",
    status: "In Progress",
  },
  {
    step: "Step 35",
    description: "Attend audit",
    assignedTo: "Wanda Maximoff",
    dueDate: "2024-06-01",
    status: "Pending",
  },
  {
    step: "Step 36",
    description: "Review audit results",
    assignedTo: "Shuri",
    dueDate: "2024-06-05",
    status: "Completed",
  },
  {
    step: "Step 37",
    description: "Implement audit recommendations",
    assignedTo: "T'Challa",
    dueDate: "2024-06-10",
    status: "Pending",
  },
  {
    step: "Step 38",
    description: "Complete project milestone",
    assignedTo: "Killmonger",
    dueDate: "2024-06-15",
    status: "In Progress",
  },
  {
    step: "Step 39",
    description: "Submit milestone report",
    assignedTo: "Okoye",
    dueDate: "2024-06-20",
    status: "Pending",
  },
  {
    step: "Step 40",
    description: "Prepare for client review",
    assignedTo: "M'Baku",
    dueDate: "2024-06-25",
    status: "Completed",
  },
  {
    step: "Step 41",
    description: "Attend client review",
    assignedTo: "Nakia",
    dueDate: "2024-06-30",
    status: "Pending",
  },
  {
    step: "Step 42",
    description: "Review client feedback",
    assignedTo: "Suri",
    dueDate: "2024-07-01",
    status: "In Progress",
  },
  {
    step: "Step 43",
    description: "Implement client feedback",
    assignedTo: "Ramonda",
    dueDate: "2024-07-05",
    status: "Pending",
  },
  {
    step: "Step 44",
    description: "Prepare for next project phase",
    assignedTo: "Ross",
    dueDate: "2024-07-10",
    status: "Completed",
  },
  {
    step: "Step 45",
    description: "Complete project phase",
    assignedTo: "Nick Fury",
    dueDate: "2024-07-15",
    status: "Pending",
  },
  {
    step: "Step 46",
    description: "Submit phase report",
    assignedTo: "Maria Hill",
    dueDate: "2024-07-20",
    status: "In Progress",
  },
  {
    step: "Step 47",
    description: "Review project timeline",
    assignedTo: "Phil Coulson",
    dueDate: "2024-07-25",
    status: "Pending",
  },
  {
    step: "Step 48",
    description: "Update project timeline",
    assignedTo: "Peggy Carter",
    dueDate: "2024-07-30",
    status: "Completed",
  },
  {
    step: "Step 49",
    description: "Prepare final deliverables",
    assignedTo: "Sharon Carter",
    dueDate: "2024-08-01",
    status: "Pending",
  },
  {
    step: "Step 50",
    description: "Submit final deliverables",
    assignedTo: "Heimdall",
    dueDate: "2024-08-05",
    status: "In Progress",
  },
  {
    step: "Step 51",
    description: "Review final deliverables",
    assignedTo: "Odin",
    dueDate: "2024-08-10",
    status: "Pending",
  },
  {
    step: "Step 52",
    description: "Sign off on project",
    assignedTo: "Frigga",
    dueDate: "2024-08-15",
    status: "Completed",
  },
  {
    step: "Step 53",
    description: "Conduct project retrospective",
    assignedTo: "Hela",
    dueDate: "2024-08-20",
    status: "Pending",
  },
  {
    step: "Step 54",
    description: "Submit retrospective report",
    assignedTo: "Laufey",
    dueDate: "2024-08-25",
    status: "In Progress",
  },
  {
    step: "Step 55",
    description: "Celebrate project completion",
    assignedTo: "Sif",
    dueDate: "2024-08-30",
    status: "Pending",
  },
  {
    step: "Step 56",
    description: "Plan next project",
    assignedTo: "Volstagg",
    dueDate: "2024-09-01",
    status: "Completed",
  },
  {
    step: "Step 57",
    description: "Kick-off next project",
    assignedTo: "Fandral",
    dueDate: "2024-09-05",
    status: "Pending",
  },
];

export {
  leadGenerationsData,
  contactTemplatesData,
  agreementTemplatesData,
  onboardingData,
};
